version: "3"

services:
  flask:
    image: finmind_flask
    build:
      context: .
      dockerfile: ./env/flask/Dockerfile
    environment:
      - TZ=Asia/Taipei
      - DEBIAN_FRONTEND=noninteractive
      - PYTHONPATH=/usr/local/bin/python
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app
    networks:
      - finmind_network

  mysql:
    image: mysql:8.0
    # 設定 mysql 使用原生認證的密碼 hash
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports: 
        - 3306:3306
    environment: # 環境變數, 設置 db, user, password, root_password
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - mysql:/var/lib/mysql
        - ./env/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
        # share volumes of docker container to outside volume, 
        # let data persist
        # 將 docker container 的 volumes 跟外部 volumes 做連結, 
        # 讓資料不會因為, container close or update, 而遺失
    networks:
        - finmind_network


networks:
  finmind_network:

volumes:
  mysql:
